%FPSOGSA with EE source code v3.0, Generated by Engr. mubashar javed, 2024. 
%Adopted from: S. Mirjalili, S.Z. Mohd Hashim, “A New Hybrid PSOGSA 
%Algorithm for Function Optimization.

function [gBest,GlobalBestCost]=Main
N = 30;                        
Max_Iteration  = 100;              

Benchmark_Function_ID=22 %(23 means IEEE 3 BUS)Benchmark function ID

[gBestScore,gBest,GlobalBestCost]= FPSOGSA(Benchmark_Function_ID, N, Max_Iteration)

gBest
gBestScore
end
